const actionTypes = {
    APP_INIT: "APP_INIT",
    ACTIVE_DAICOS_FAILED: "ACTIVE_DAICOS_FAILED",
    ACTIVE_DAICOS_SUCCESS: "ACTIVE_DAICOS_SUCCESS",
    SHOW_ACTIVE_DAICOS_LOADER: "SHOW_ACTIVE_DAICOS_LOADER",
    ENDED_DAICOS_FAILED: "ENDED_DAICOS_FAILED",
    ENDED_DAICOS_SUCCESS: "ENDED_DAICOS_SUCCESS",
    SHOW_ENDED_DAICOS_LOADER: "SHOW_ENDED_DAICOS_LOADER",
    UPCOMING_DAICOS_FAILED: "UPCOMING_DAICOS_FAILED",
    UPCOMING_DAICOS_SUCCESS: "UPCOMING_DAICOS_SUCCESS",
    SHOW_UPCOMING_DAICOS_LOADER: "SHOW_UPCOMING_DAICOS_LOADER", 
}

export default actionTypes;
